wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=s3cr3t
    ports:
     - "0.0.0.0:81:80"
    volumes:
     - ./code:/code
     - ./html:/var/www/html
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=s3cr3t
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
